node *ptr=NULL;
    // linkedlist list;
    // //list.deletefront(&ptr); 
    // list.push_front(&ptr,30);
    // list.push_front(&ptr,20);
    // list.push_front(&ptr,10);
    // list.push_after(ptr,50,1);
    // list.push_after(ptr,40,2);
    // list.push_before(ptr,70,2);
    // list.push_back(&ptr,60);
    // list.deleteat(&ptr,2);
    // list.display(ptr);
    // //cout<<ptr->data;
    // //list.deletefront(&ptr);
    // //list.deleterear(&ptr);
    // //free(ptr);
    // //list.display(ptr);
